CREATE DATABASE ALFA;
GO

-- CASO 1
CREATE TABLE EMPLEADO(
ID INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
USUARIO VARCHAR(20) NULL,
CLAVE VARCHAR(20) NULL
);
GO

INSERT INTO EMPLEADO VALUES(1,'JUAN PEREZ','JPEREZ','SECRETO');
INSERT INTO EMPLEADO VALUES(2,'ANA CONTRERAS',NULL,NULL);
GO

SELECT * FROM EMPLEADO;
GO

DROP TABLE EMPLEADO;
GO

CREATE TABLE EMPLEADO(
ID INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE USUARIO(
ID INT NOT NULL PRIMARY KEY,
USUARIO VARCHAR(20) NOT NULL,
CLAVE VARCHAR(20) NOT NULL,
CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (ID) REFERENCES EMPLEADO
);
GO

INSERT INTO EMPLEADO VALUES(1,'JUAN PEREZ');
INSERT INTO EMPLEADO VALUES(2,'ANA CONTRERAS');
GO

SELECT * FROM EMPLEADO;
GO

INSERT INTO USUARIO VALUES(1,'JPEREZ','SECRETO');
GO

SELECT * FROM USUARIO;
GO






